#!/usr/bin/env bash
#
# Fetches the three families the interface is set in — Spectral, IBM Plex Sans
# and IBM Plex Mono — as subsetted woff2 files, and writes the @font-face sheet
# that names them. The app's CSP is `default-src 'self'`, so the faces have to
# travel inside the bundle; this script is the only writer of
# `ui/src/styles/fonts/` and of `ui/src/styles/fonts.css`, and both are
# committed. Re-running it against the pinned versions must leave
# `git status --porcelain ui/src/styles` empty — that is how a reviewer checks
# the committed bytes are the ones the pins describe.
#
# Source: the Google Fonts CSS API, which serves per-script woff2 subsets with a
# `unicode-range` each, so a Latin-only page never downloads Cyrillic glyphs and
# a Ukrainian page gets both. Only the four subsets below are kept: latin and
# latin-ext (a Polish or Czech file name renders in one face), cyrillic (the
# Ukrainian alphabet, `№`) and cyrillic-ext — which is where `₴` (U+20B4) lives,
# not in cyrillic. Vietnamese and Greek are served too and dropped here.
#
# The version segment of every file URL (`/s/<family>/<vN>/`) must equal the
# pin below; a newer upstream version fails the run rather than silently
# replacing the committed files. The API needs a browser User-Agent to answer
# with woff2 and unicode-range at all — an unknown agent gets a single TTF.
#
# IBM Plex Sans is served as a VARIABLE font (one `wght` axis, 100–700), so it
# is asked for as a weight range and comes back as one file per subset with
# `font-weight: 400 600`. Asked for as `wght@400;500;600` instead, the API
# answers three blocks per subset that all point at the SAME file — eight
# byte-identical copies in the bundle, which is how this was first fetched.
# Spectral and IBM Plex Mono are static families and are asked for by weight.
# The check after each family's loop turns that shape into a hard failure: two
# faces of one family sharing a file means the query should have been a range.
#
# Usage: scripts/fetch-fonts.sh
#
# Result: ui/src/styles/fonts/<slug>/<slug>-<weight>-<style>-<subset>.woff2,
#         ui/src/styles/fonts/<slug>/OFL.txt, ui/src/styles/fonts.css

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
styles="${repo_root}/ui/src/styles"
dest="${styles}/fonts"
sheet="${styles}/fonts.css"

API="https://fonts.googleapis.com/css2"
OFL_BASE="https://raw.githubusercontent.com/google/fonts/main/ofl"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36"
SUBSETS="latin latin-ext cyrillic cyrillic-ext"

# slug | google/fonts directory | pinned version segment | css2 family query
FAMILIES=(
  "spectral|spectral|v15|Spectral:ital,wght@0,400;0,600;1,400"
  "ibm-plex-sans|ibmplexsans|v23|IBM+Plex+Sans:wght@400..600"
  "ibm-plex-mono|ibmplexmono|v20|IBM+Plex+Mono:wght@400;500"
)

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

rm -rf "$dest"
mkdir -p "$dest"

{
  echo "/* Bundled faces — GENERATED by scripts/fetch-fonts.sh; do not edit by hand,"
  echo " * re-run the script. Only @font-face blocks belong here; the stacks that"
  echo " * name these families live in tokens.css, and tokens.test.ts checks that"
  echo " * every url() below exists, every file is named, and every face covers"
  echo " * the Ukrainian alphabet and the hryvnia sign. font-display: block — the"
  echo " * files are local, so a flash of fallback type is worse than a 0 ms wait."
  echo " */"
} > "$sheet"

for entry in "${FAMILIES[@]}"; do
  IFS='|' read -r slug gfdir version query <<< "$entry"
  echo "== ${slug} (${version})"
  mkdir -p "${dest}/${slug}"

  curl -fsSL -A "$UA" -o "${tmp}/${slug}.css" "${API}?family=${query}&display=block"
  curl -fsSL -o "${dest}/${slug}/OFL.txt" "${OFL_BASE}/${gfdir}/OFL.txt"

  # One perl pass over the API's sheet: keep the wanted subsets, check the pin,
  # download each file under a name that says what it is, and print the block
  # again with a relative url(). Blocks come back in the API's own order, so
  # the output is stable across runs as long as upstream is.
  perl - "$slug" "$gfdir" "$version" "${tmp}/${slug}.css" "${dest}/${slug}" "$SUBSETS" <<'PERL' >> "$sheet"
use strict; use warnings;
my ($slug, $gfdir, $version, $css_path, $dir, $subsets) = @ARGV;
my %keep = map { $_ => 1 } split ' ', $subsets;
open my $fh, '<', $css_path or die "open $css_path: $!";
local $/; my $css = <$fh>; close $fh;
my $n = 0;
while ($css =~ m{/\* (\S+) \*/\s*\@font-face \{(.*?)\}}sg) {
  my ($subset, $body) = ($1, $2);
  next unless $keep{$subset};
  my ($family) = $body =~ /font-family:\s*'([^']+)'/ or die "$slug: no font-family in a block";
  my ($style)  = $body =~ /font-style:\s*(\w+)/      or die "$slug: no font-style";
  # `400` for a static face, `400 600` for a variable one's range.
  my ($weight) = $body =~ /font-weight:\s*(\d+(?: \d+)?);/ or die "$slug: no font-weight";
  my ($url)    = $body =~ /url\(([^)]+)\)/           or die "$slug: no url()";
  my ($range)  = $body =~ /unicode-range:\s*([^;]+);/ or die "$slug: no unicode-range";
  $url =~ m{/s/\Q$gfdir\E/\Q$version\E/} or die "$slug: $url is not $gfdir/$version — the pin moved";
  (my $weight_slug = $weight) =~ s/ /-/g;
  my $name = "$slug-$weight_slug-$style-$subset.woff2";
  system('curl', '-fsSL', '-o', "$dir/$name", $url) == 0 or die "$slug: download of $name failed";
  print "/* $family $weight $style — $subset */\n";
  print "\@font-face {\n";
  print "  font-family: '$family';\n";
  print "  font-style: $style;\n";
  print "  font-weight: $weight;\n";
  print "  font-display: block;\n";
  print "  src: url(./fonts/$slug/$name) format('woff2');\n";
  print "  unicode-range: $range;\n";
  print "}\n";
  $n++;
}
die "$slug: no \@font-face block matched — the API answered without woff2 subsets?" unless $n;
print STDERR "   $n faces\n";
PERL

  # Two faces of one family must not share a file. When they do, the API is
  # serving a variable font instanced by nothing — the query has to be a
  # weight range (see the header), and the sheet has to say so.
  total=$(ls "${dest}/${slug}"/*.woff2 | wc -l | tr -d ' ')
  distinct=$(shasum -a 256 "${dest}/${slug}"/*.woff2 | cut -d' ' -f1 | sort -u | wc -l | tr -d ' ')
  if [ "$total" != "$distinct" ]; then
    echo "${slug}: ${total} files but only ${distinct} distinct — faces share a file; ask for a weight range" >&2
    exit 1
  fi
done

echo "== size"
du -ch "${dest}"/*/*.woff2 | tail -1
